### ISSUE TITLE
More options for URL filtering/cleaning

### ISSUE THREAD

**Issue by Faberman** [tumpio/requestcontrol#10] opened 2017-05-05 14:44 UTC
Hello.
I was looking for Clean Links replacement and found this great extension. But I think it can be improved in terms of link cleaning. A few suggestions:

-  Global URL parameters filtering (for any url, even without rules). At the moment parameters are only removed from requests that match any "Filter" rule . I tried to add a global filter rule with `Pattern: Any URL`, but it doesn't work;
- Two global whitelists for hosts and paths or even better -> see the next paragraph;
- Ability to use multiple hosts and paths in rules. And instead of 'Include subdomains' checkbox, just use wildcard `*`. Often redirection/affiliate links use identical schemes (?r=, ?url=), so creating separate rules for each host is excessive. Also one could create a whitelist rule with multiple hosts - no need for a separate global whitelist;
- Wildcard support for URL parameters (like `utm_*`, `ref_*`). Not really necessary though.

Here is a concept: https://dl.dropboxusercontent.com/s/h131h58h6aoiqc4/requestcontrol2.png

Also a question. Which regex flavor is used in this extension? Javascript? I'm trying to create a redirection rule to get direct links to Dropbox, but I can't get it to work. Here is the rule: `{href/.*www\.dropbox\.com(\/s\/.+\/.+)\?dl=\d/https://dl.dropboxusercontent.com$1}`
Test link: https://www.dropbox.com/s/h131h58h6aoiqc4/requestcontrol2.png?dl=0

--
To do list for these:
- [x] Fix url parameter filtering for global rules.
- [x] Fix redirection url parsing from a query string (remove trailing query parameters).
- [x] Change global url parameter trimming to Filter rule specific.
- [x] Add a button to toggle redirection cleaning for "Filter" action.
- [x] Add Wildcard support for URL parameters (like utm_*, ref_*).
- [x] Use only * instead of 'Include subdomains' checkbox.
- [x] Add support for including multiple match patterns for rules.

note the rules priority issue.

**Comment by tumpio** [comment] 2017-05-07 09:51
Hi there. These are good suggestions. The first one sounds like a bug. Support for adding multiple match patterns (hosts, paths) for rules can be added. Most of it will be UI related work. A rule with multiple match patterns would just add multiple webRequest API request listeners. I'll work on these when I have some free time. Any help is appreciated.

To do list for these:
- [ ] Fix url parameter filtering for global rules.
- [ ] Add support for including multiple pattern matches for rules.
- [ ] Use only * instead of 'Include subdomains' checkbox.
- [ ] Add Wildcard support for URL parameters (like utm_*, ref_*).

> 
Also a question. Which regex flavor is used in this extension? Javascript? I'm trying to create a redirection rule to get direct links to Dropbox, but I can't get it to work. Here is the rule: {href/.*www\.dropbox\.com(\/s\/.+\/.+)\?dl=\d/https://dl.dropboxusercontent.com$1}

Oh, I have forgotten to release the fixed version.. I'll do it shortly but you can also try the beta version that includes a fix for this:
https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.4.2beta1

**Comment by tumpio** [comment] 2017-05-07 17:11
I fixed the first issue with global url param filtering. Can you confirm that it's fixed:
https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.4.3beta1

**Comment by Faberman** [comment] 2017-05-07 18:34
Thank you!
Regex and `Any URL` filter work just fine now.
I've made a webpage with a few links for testing: http://pipes.droppages.com/links

**Comment by tumpio** [comment] 2017-05-08 14:31
> Regex behavior is strange. With Any URL filter rule enabled I can't get this regex pattern to work: {href/.*site\.com\/away\.php\?to=(.*?)&cc_key=.*/$1}
> It should clean up this type of URL: https://site.com/away.php?to=https://github.com&cc_key=.
> At the same time regex for Dropbox links works.

For me it redirects to https://github.com&cc_key=. Is this what happens also for you? I don't understand why the "&acc_key=" remains. The url that is given for the request resolver is only "https://github.com" when I'm inspecting it with debugger.

> Also with Any URL filter rule disabled, all the links with redirection, but without parameters get skipped by addon. For example:

Can you tell me step by step how to reproduce this? Which rules do you have enabled and which disabled?

**Comment by tumpio** [comment] 2017-05-08 14:56
I investigate the site.com redirection issue more. I think the problem is with how the promise is being resolved.

**Comment by Faberman** [comment] 2017-05-08 15:08
> For me it redirects to https://github.com&cc_key=. Is this what happens also for you?

Yes. &cc_key= remains and therefore website can't be loaded. With Any URL filter rule disabled or removed, this regex works as expected. Steps to reproduce:

1. Create a Filter rule with Pattern: Any URL; Types: Document and enable it.
2. Create a Redirect rule with Pattern: `{href/.*site\.com\/away\.php\?to=(.*?)&cc_key=.*/$1}`; Types: Document and enable it.
3. Click on https://site.com/away.php?to=https://github.com&cc_key=
Result will be https://github.com&cc_key=/
4. Disable Filter rule with Pattern: Any URL.
5. Click on https://site.com/away.php?to=https://github.com&cc_key=
Result will be https://github.com

> Can you tell me step by step how to reproduce this?

My bad. It turns out I've accidentally removed a rule for steamcommunity.com. But I've just found another bug: with Any URL rule enabled other rules keep working even if you disable them. Steps to reproduce:

1. Create a Filter rule with Pattern: Any URL; Types: Document and enable it.
2. Disable any other rule (for example, filter rule steamcommunity.com).
3. Click on https://steamcommunity.com/linkfilter/?url=https://addons.mozilla.org/
Result will be https://addons.mozilla.org/ - rule is disabled, but redirection works.

**Comment by tumpio** [comment] 2017-05-08 18:14
I get the issue now. It's actually problem of two things. First, if multiple rules match a single request, only the action of the first rule gets applied. This is how the webRequest API resolves the request listeners. Second, the default "Filter" action does not strip trailing search parameters from the filtered url if is not encoded. If I remember right some redirection pattern followed this practice. 

I'm not certain how these should be fixed. I can change it so that global rules (Any URL) will be set after other rules. This way any site specific rule will get a preference to the global rules. 

Do you have other ideas?

**Comment by Faberman** [comment] 2017-05-09 01:12
> First, if multiple rules match a single request, only the action of the first rule gets applied.

How about removing that global URL parameters list from the bottom and just adding an additional field to the Filter rules? Also you can add a button to trim all parameters by default - it might be useful for site specific rules. So, trimming should be applied only to Filters, because regular expressions allow you to do anything you want anyway.
Here is another concept: https://dl.dropboxusercontent.com/s/i4qcdyabt4yezns/requestcontrol4.png
Just my thoughts, it might be too difficult to implement all this stuff.

> Second, the default "Filter" action does not strip trailing search parameters from the filtered url if is not encoded.

But URL can be encoded/decoded before processing, right? encodeURI/decodeURI/unescape

> I can change it so that global rules (Any URL) will be set after other rules. This way any site specific rule will get a preference to the global rules.

Yes, I think site specific rules should have a priority.

P. S. Here is an old bookmarklet: https://pastebin.com/wLxJqGf1. It does a pretty good job at removing redirections with or without parameters, either encoded or decoded. Maybe you would find it useful.

**Comment by tumpio** [comment] 2017-05-09 12:20
Another beta version for you to test.  I fixed the default "Filter" action redirection url parsing from a query string that contains additional search parameters separated by ("&" or ";"). Encoded url parameters are kept unlike in the bookmarklet you shared.

https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.4.3beta2

**Comment by Faberman** [comment] 2017-05-09 16:23
"Curiosier and curiosier!"
I've tested different scenarios on [test page](http://pipes.droppages.com/links). + is a good thing, - is a bad thing.

1. Any URL rule doesn't exist:
 - Pre-defined rule for Google (№6 on test page) doesn't work;
 + All other rules work as expected.
 + Links 11, 12, 13 don't get filtered (this is totally fine, because there are no special rules for them);
2. Any URL rule exists and is disabled:
 - Pre-defined rule for Google (№6 on test page) doesn't work;
 + All other rules work as expected.
 + Links 11, 12, 13 don't get filtered (this is totally fine, because there are no special rules for them);
3. Any URL rule exists and is enabled:
 + All rules work as expected, all links get filtered.
4. Any URL rule exists and is enabled, but *all other rules are disabled*:
 + Rules №10 (Amazon) and №14 (Dropbox) don't work;
 - All other rules work, links get filtered. And this is definitely not as expected.

**Comment by tumpio** [comment] 2017-05-09 17:54
> - Pre-defined rule for Google (№6 on test page) doesn't work;

Fixed this one. The pre-defined rule was missing "main_frame" in types.

>  - All other rules work. And this is definitely not as expected. I mean the only purpose of Any URL filter rule is trimming URL parameters, not cleaning redirections.

Hmm, I see. Would a toggle button to turn the redirection cleaning on/off for the "Filter" action suffice? Currently the Filter action always does both the redirection cleaning and global url parameters filtering. I will also add the list of trimmed url parameters to the Filter rule instead of having the global list.

**Comment by Faberman** [comment] 2017-05-09 18:20
> Would a toggle button to turn the redirection cleaning on/off for the "Filter" action suffice?

Sounds good to me. With a global list it could be a bit confusing, but it will definitely work with per-site lists.

**Comment by tumpio** [comment] 2017-05-29 17:54
@Faberman Can you test new beta version?
https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/versions/1.5.0beta1

Changes in this version:
URL parameter filtering is now Filter rule specific.
Redirection cleaning can be now turned off in Filter rule.
And added wildcard "*" support for url parameter trimming.

**Comment by Faberman** [comment] 2017-05-29 19:23
Everything seems to work fine, but URL parameters trimming is a bit confusing.
For example, this url: http://site3.com/?r=https%3A%2F%2Fwww.yr.no%2Fplace%2FNorway%2FNordland%2FBr%C3%B8nn%C3%B8y%2FBr%C3%B8nn%C3%B8ysund%2Fhour_by_hour.html?key=ms&ww=51802

With URL parameters trimming disabled I get `[...].html?key=ms`, but it should be `[...].html?key=ms&ww=51802`, if i'm not mistaken. With 'Trim all' enabled I get `[...].html` as expected.

That's fine for me, because in most cases I want URL parameters to be cleaned. So, just an observation. :)

Thank you for improving this great extension!

**Comment by tumpio** [comment] 2017-05-29 20:58
Thanks for testing. That problem is with the url redirection cleaning and in the redirection address extraction. I'm expecting to remove the query parameters of the original url and not to include them in the final redirection address. That url is exceptional because it is not encoding the query string of the redirection address and as such the "ww" parameter is actually interpreted to be a url parameter of site3.com and not yr.no. 

This is actually how the Firefox URL interface also reads that address. It reads it as a url of site3.com with a query string that contains two parameters "r" and "ww".

So for this special case I would write a custom redirect rule with regular expression :)

**Comment by Faberman** [comment] 2017-05-29 21:40
Got it. Anyway, some of the patterns on my test page are intended for testing purposes only and most users probably will not encounter them.

So, now the extension can be considered "full-featured". As for the multiple match patterns, I think most users will use this feature for whitelists, so maybe it will be easier to implement two global whitelists for hosts and paths. The less code the better.

**Comment by tumpio** [comment] 2017-05-30 06:46
Yes thanks for creating the test page. It helps to debug the add-on in future as well when I do changes and if things go wrong. Can I mention the test page in add-on description? And if hosting is problem we could place it to as a wiki page in here. https://github.com/tumpio/requestcontrol/wiki

I think I'll still go with the multi match pattern way so that it's possible to set up own global whitelist rule with multiple hosts and paths.

**Comment by Faberman** [comment] 2017-05-30 10:35
Sure. Wiki is better, because you can edit it if necessary.
Page source: https://dl.dropboxusercontent.com/s/3idit4f65oc4clc/links.txt

**Comment by tumpio** [comment] 2017-05-30 11:22
Ok, it's here now:
https://github.com/tumpio/requestcontrol/wiki/Testing-page-for-redirection-filtering

The wiki is public so you are able to edit it directly.

**Comment by tumpio** [comment] 2017-06-04 11:56
Here's new beta version for testing that adds support for the adding multiple hosts and paths for rules:
https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.6.0beta3

**Comment by Faberman** [comment] 2017-06-04 13:57
After a quick test everything seems to work fine, except one thing: it's impossible to save `*` (any domain) in hosts. And if you create a whitelist with an empty host field, all filter rules will stop working.

**Comment by tumpio** [comment] 2017-06-05 08:39
Fixed them in 
https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.6.0beta4

**Comment by Faberman** [comment] 2017-06-06 12:54
Awesome. Yes, now everything is ok.

And the last suggestion. How about combining different rule types into sections to visually separate them? Just like you did it for Whitelist rules: https://dl.dropboxusercontent.com/s/d1uj359zoa9pgsd/requestcontrol5.png

**Comment by tumpio** [comment] 2017-06-07 07:06
Looks great! I've also thought about adding separate tabs for each rule type.

**Comment by tumpio** [comment] 2017-06-12 08:09
@Faberman a new beta! :P 

I added support for multiple rule matching for single request. This allows to create e.g. a global rule to trim url parameters while having other site specific rules. If more than one redirect or filter rule applies to a single request they will be applied one by one.

Also the rules follow this priority model:
1. whitelist rule
2. block rule
3. redirect rule
4. filter rule

Whitelist rules has the top priority and revokes all other rules. Next is the block rules and they revoke redirect and filter rules. Finally redirect rules will be applied before filter rules, but all of them will still be applied.

https://addons.mozilla.org/addon/requestcontrol/versions/1.6.0beta5

This version needs restoring default rules if you have created any whitelist rules.

**Comment by Faberman** [comment] 2017-06-12 20:30
Nice! I didn't even know that addon couldn't process multiple rules.

As for the 1.6.0beta7, Redirect rules with regex pattern (Dropbox links, for example) don't work.

**Comment by tumpio** [comment] 2017-06-13 10:52
Fixed redirection rules and added sections for each rule types in options. 

I released 1.6.0. Will close this issue now, for new suggestions it's better to open new page :)

Thanks for the help!

**Closed by tumpio** 2017-06-13 10:52 UTC
Labels: enhancement, help wanted

**Comment by tumpio** [comment] 2017-06-13 11:13
> Nice! I didn't even know that addon couldn't process multiple rules.

Yeah, I finally figured out how to work around the webRequest API limitation. It's a big change in background but should not affect anything else.
