### ISSUE TITLE
Question mark in path is interpreted as regex quantifier

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#65] opened 2018-05-14 23:04 UTC
### Expected behavior
The question mark in the `url?*` path of the default Google rule to be interpreted literally.

### Actual behavior
It is being interpreted as a regex ? special character. Test it against `https://www.google.com/ur`.

If that's the new intended behavior, that question mark should be escaped (it cannot be) or just removed. 

Request Control 1.9.1
Firefox 60

**Comment by tumpio** [comment] 2018-05-15 14:58
I couldn't reproduce this. How did you test it?

**Comment by tumpio** [comment] 2018-05-15 17:12
fixed in https://github.com/tumpio/requestcontrol/commit/10fc0d10c51728712dc0522929fd51f4ffbb7726

**Closed by tumpio** 2018-05-15 17:12 UTC
Labels: bug
