### ISSUE TITLE
mobile.twitter.com -> twitter.com redirect issue

### ISSUE THREAD

**Issue by zmni** [tumpio/requestcontrol#62] opened 2018-05-10 12:43 UTC
> Firefox 60 x64
> Request Control v1.9.0

### Expected behavior
Redirect to `https://twitter.com/*`

### Actual behavior
Doesn't redirect.

### Steps to reproduce the problem
Add this rule:
```
[
  {
    "pattern": {
      "scheme": "*",
      "host": [
        "mobile.twitter.com"
      ],
      "path": [
        "*"
      ]
    },
    "types": [
      "main_frame"
    ],
    "action": "redirect",
    "active": true,
    "redirectUrl": "[hostname=twitter.com]",
    "id": "11"
  }
]
```
I also try `{href}` regex replacement on `redirectUrl`: `{href/https?:\/\/mobile\.twitter\.com(\/.*)?/https://twitter.com$1}`.

**Comment by tumpio** [comment] 2018-05-12 07:02
I couldn't reproduce this. Are other rules working for you with version 1.9.0?

**Comment by zmni** [comment] 2018-05-12 11:44
Maybe this issue happened because I *edit existing rule*? Chronologically like this:

1. RequestControl first installed version `1.8.6`. In this version I created a rule that redirect `twitter.com` to `mobile.twitter.com` (the opposite of above rule). It work but doesn't always active, sometimes I enabled it, sometimes I disabled it. In the end, I disabled it until before this bug report.

2. After this addon updated to version `1.9.0` I edit the rule, change `host` to `mobile.twitter.com` and `redirectUrl` to `twitter.com`. Enable it and test the rule by clicking link on reddit, even manually copy paste enter the link to urlbar, it doesn't work. I then export, delete & import the rule, doesn't work. And finally, I delete the rule, create new with exact entry but still doesn't work.

That's the whole process.

One thing I have not tried is to restart from scratch (uninstall requestcontrol, restart firefox, redo all the rules). But I can surely guess the above rule will work if it created from scratch (new addon install).

And for the other rules, I never edit or change anything, and all working just fine.

**Comment by tumpio** [comment] 2018-05-12 17:29
Could you export all rules and attach the file here? Or send it to me to tumpio@post.com

**Comment by zmni** [comment] 2018-05-12 18:11
[request-control-rules.zip](https://github.com/tumpio/requestcontrol/files/1997793/request-control-rules.zip) or [gist](https://gist.github.com/zmni/1da8e10eb0b32e4178abd625198c202a)

Could it be because of PWA? This progressive cache, low bandwidth, offline feature thing may be the reason why RequestControl is not working as it should.

**Comment by tumpio** [comment] 2018-05-15 16:26
I think you are right. Today I tried to debug it again and it started to happen. It is not triggering the "main_frame" request which the rule is bind to. Once I removed the browser cache it started to work again. Can you also try to clear the cache and offline web site data? I removed all expect browser history and downloads data.

**Comment by zmni** [comment] 2018-05-21 14:38
Yes, I can reproduced it. Should I close this or leave it open?

**Comment by tumpio** [comment] 2018-05-25 19:43
Let's keep it open. I'm not certain how the WebRequest API should work here. Need to ask or submit bug for it.

**Comment by tumpio** [comment] 2018-06-30 17:57
This should be fixed by Firefox 61. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1448599

**Closed by tumpio** 2018-06-30 17:57 UTC
Labels: bug, more info needed
